depth_multiple: 0.33  # model depth multiple
width_multiple: 0.25  # layer channel multiple

backbone:
  # [from, number, module, args]
  [[-1, 1, RepVGGBlock, [64, 3, 2]],  # 0-P1/2
   [-1, 1, RepVGGBlock, [128, 3, 2]],  # 1-P2/4
   [-1, 6, RepBlock, [128]],
   [-1, 1, RepVGGBlock, [256, 3, 2]],  # 3-P3/8
   [-1, 12, RepBlock, [256]],
   [-1, 1, RepVGGBlock, [512, 3, 2]],  # 5-P4/16
   [-1, 18, RepBlock, [512]],
   [-1, 1, RepVGGBlock, [1024, 3, 2]],  # 7-P5/32
   [-1, 6, RepBlock, [1024]],
   [-1, 1, SimSPPF, [1024, 5]]]  # 9

neck:
  [[-1, 1, SimConv, [256, 1, 1]], # 10
   [-1, 1, Transpose, [256]],     # 11
   [[-1, 6], 1, Concat, [1]],     # 12
   [-1, 12, RepBlock, [256]],     # 13

   [-1, 1, SimConv, [128, 1, 1]], # 14
   [-1, 1, Transpose, [128]],     # 15
   [[-1, 4], 1, Concat, [1]],     # 16
   [-1, 12, RepBlock, [128]],     # 17 out

   [-1, 1, SimConv, [128, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 12, RepBlock, [256]],  # 20 (P4/16-medium)

   [-1, 1, SimConv, [256, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 12, RepBlock, [512]]]  # 23 (P5/32-large)

effidehead:
  [[17, 1, Head_layers, [128, 0]],#if use_dfl is False, please set reg_max to 0
  [20, 1, Head_layers, [256, 0]],
  [23, 1, Head_layers, [512, 0]],
  [[24, 25, 26],1,Out, []]]


